-- MySQL Script generated by MySQL Workbench
-- 03/31/16 11:50:42
-- Model: hmat    Version: 0.1

-- work flow monitor

-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hmat
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hmat` ;

-- -----------------------------------------------------
-- Schema hmat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hmat` DEFAULT CHARACTER SET utf8 COLLATE utf8_slovak_ci ;
USE `hmat` ;

-- -----------------------------------------------------
-- Table `hmat`.`Industry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmat`.`Industry` ;

CREATE TABLE IF NOT EXISTS `hmat`.`Industry` (
  `idIndustry` INT NOT NULL AUTO_INCREMENT,
  `IndustryShortcut` VARCHAR(5) NOT NULL,
  `IndustryName` VARCHAR(45) NULL,
  PRIMARY KEY (`idIndustry`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmat`.`Company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmat`.`Company` ;

CREATE TABLE IF NOT EXISTS `hmat`.`Company` (
  `idCompany` INT NOT NULL AUTO_INCREMENT,
  `Industry_idIndustry` INT NOT NULL,
  `CompanyName` VARCHAR(30) NULL,
  `CompanyICO` VARCHAR(25) NULL,
  `CompanyDIC` VARCHAR(25) NULL,
  `CompanyDRC` VARCHAR(20) NULL,
  `CompanyWebsite` VARCHAR(45) NULL,
  PRIMARY KEY (`idCompany`, `Industry_idIndustry`),
  INDEX `fk_Company_Industry1_idx` (`Industry_idIndustry` ASC),
  CONSTRAINT `fk_Company_Industry1`
    FOREIGN KEY (`Industry_idIndustry`)
    REFERENCES `hmat`.`Industry` (`idIndustry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmat`.`Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmat`.`Address` ;

CREATE TABLE IF NOT EXISTS `hmat`.`Address` (
  `idAddress` INT NOT NULL AUTO_INCREMENT,
  `Company_idCompany` INT NOT NULL,
  `AddressName` VARCHAR(45) NULL,
  `AddressStreet` VARCHAR(60) NULL,
  `AddressNumber` VARCHAR(20) NULL,
  `AddressZip` VARCHAR(10) NULL,
  `AddressCity` VARCHAR(30) NULL,
  `AddressCountry` VARCHAR(30) NULL,
  PRIMARY KEY (`idAddress`, `Company_idCompany`),
  INDEX `fk_Address_Company1_idx` (`Company_idCompany` ASC),
  CONSTRAINT `fk_Address_Company1`
    FOREIGN KEY (`Company_idCompany`)
    REFERENCES `hmat`.`Company` (`idCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmat`.`Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmat`.`Account` ;

CREATE TABLE IF NOT EXISTS `hmat`.`Account` (
  `idAccount` INT NOT NULL AUTO_INCREMENT,
  `Company_idCompany` INT NOT NULL,
  `AccountName` VARCHAR(30) NULL,
  `AccountBank` VARCHAR(30) NULL,
  `AccountVAT` VARCHAR(45) NULL,
  `AccountIBAN` VARCHAR(30) NULL,
  PRIMARY KEY (`idAccount`, `Company_idCompany`),
  INDEX `fk_Account_Company1_idx` (`Company_idCompany` ASC),
  CONSTRAINT `fk_Account_Company1`
    FOREIGN KEY (`Company_idCompany`)
    REFERENCES `hmat`.`Company` (`idCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmat`.`Partner_has_Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmat`.`Partner_has_Account` ;

CREATE TABLE IF NOT EXISTS `hmat`.`Partner_has_Account` (
  `Partner_idPartner` INT NOT NULL,
  `Account_idAccount` INT NOT NULL,
  PRIMARY KEY (`Partner_idPartner`, `Account_idAccount`),
  INDEX `fk_Partner_has_Account_Account1_idx` (`Account_idAccount` ASC),
  INDEX `fk_Partner_has_Account_Partner1_idx` (`Partner_idPartner` ASC),
  CONSTRAINT `fk_Partner_has_Account_Partner1`
    FOREIGN KEY (`Partner_idPartner`)
    REFERENCES `hmat`.`Company` (`idCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partner_has_Account_Account1`
    FOREIGN KEY (`Account_idAccount`)
    REFERENCES `hmat`.`Account` (`idAccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmat`.`Person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmat`.`Person` ;

CREATE TABLE IF NOT EXISTS `hmat`.`Person` (
  `idPerson` INT NOT NULL AUTO_INCREMENT,
  `Company_idCompany` INT NOT NULL,
  `PersonName` VARCHAR(20) NULL,
  `PersonSurname` VARCHAR(45) NULL,
  `PersonPostition` VARCHAR(20) NULL,
  `PersonPhone` VARCHAR(30) NULL,
  `PersonEmail` VARCHAR(45) NULL,
  PRIMARY KEY (`idPerson`, `Company_idCompany`),
  INDEX `fk_Person_Company1_idx` (`Company_idCompany` ASC),
  CONSTRAINT `fk_Person_Company1`
    FOREIGN KEY (`Company_idCompany`)
    REFERENCES `hmat`.`Company` (`idCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmat`.`Project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmat`.`Project` ;

CREATE TABLE IF NOT EXISTS `hmat`.`Project` (
  `idProject` INT NOT NULL AUTO_INCREMENT,
  `Company_idCompany` INT NOT NULL,
  `ProjectStartDate` DATETIME NULL,
  `ProjectStatus` VARCHAR(20) NULL,
  `ProjectName` VARCHAR(45) NULL,
  `ProjectPriority` INT NULL,
  PRIMARY KEY (`idProject`, `Company_idCompany`),
  INDEX `fk_Project_Company1_idx` (`Company_idCompany` ASC),
  CONSTRAINT `fk_Project_Company1`
    FOREIGN KEY (`Company_idCompany`)
    REFERENCES `hmat`.`Company` (`idCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmat`.`PrintParameters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmat`.`PrintParameters` ;

CREATE TABLE IF NOT EXISTS `hmat`.`PrintParameters` (
  `idPrintParameters` INT NOT NULL AUTO_INCREMENT,
  `PrintParametersTechnology` VARCHAR(20) NULL,
  `PrintParametersMaterial` VARCHAR(20) NULL,
  `PrintParametersResolution` VARCHAR(20) NULL,
  `PrintParametersLayer` VARCHAR(20) NULL,
  `PrintParametersFinish` VARCHAR(40) NULL,
  PRIMARY KEY (`idPrintParameters`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmat`.`Quote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmat`.`Quote` ;

CREATE TABLE IF NOT EXISTS `hmat`.`Quote` (
  `idQuote` INT NOT NULL AUTO_INCREMENT,
  `Project_idProject` INT NOT NULL,
  `PrintParameters_idPrintParameters` INT NOT NULL,
  `QuoteStatus` VARCHAR(15) NULL,
  `QuoteLeadTime` TIME(6) NULL,
  `QuotePrice` FLOAT NULL,
  `QuoteDateSent` DATETIME NULL,
  PRIMARY KEY (`idQuote`, `Project_idProject`, `PrintParameters_idPrintParameters`),
  INDEX `fk_Quote_Project1_idx` (`Project_idProject` ASC),
  INDEX `fk_Quote_PrintParameters1_idx` (`PrintParameters_idPrintParameters` ASC),
  CONSTRAINT `fk_Quote_Project1`
    FOREIGN KEY (`Project_idProject`)
    REFERENCES `hmat`.`Project` (`idProject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Quote_PrintParameters1`
    FOREIGN KEY (`PrintParameters_idPrintParameters`)
    REFERENCES `hmat`.`PrintParameters` (`idPrintParameters`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmat`.`DataSet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmat`.`DataSet` ;

CREATE TABLE IF NOT EXISTS `hmat`.`DataSet` (
  `idDataSet` INT NOT NULL AUTO_INCREMENT,
  `PrintParameters_idPrintParameters` INT NOT NULL,
  `Quote_idQuote` INT NOT NULL,
  `DataSetName` VARCHAR(30) NULL,
  `DataSetStatus` VARCHAR(20) NULL,
  `DataSetDate` DATETIME NULL,
  PRIMARY KEY (`idDataSet`, `PrintParameters_idPrintParameters`, `Quote_idQuote`),
  INDEX `fk_DataSet_Quote1_idx` (`Quote_idQuote` ASC),
  INDEX `fk_DataSet_PrintParameters1_idx` (`PrintParameters_idPrintParameters` ASC),
  CONSTRAINT `fk_DataSet_Quote1`
    FOREIGN KEY (`Quote_idQuote`)
    REFERENCES `hmat`.`Quote` (`idQuote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DataSet_PrintParameters1`
    FOREIGN KEY (`PrintParameters_idPrintParameters`)
    REFERENCES `hmat`.`PrintParameters` (`idPrintParameters`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmat`.`Part`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmat`.`Part` ;

CREATE TABLE IF NOT EXISTS `hmat`.`Part` (
  `idPart` INT NOT NULL AUTO_INCREMENT,
  `DataSet_idDataSet` INT NOT NULL,
  `PrintParameters_idPrintParameters` INT NOT NULL,
  `PartStatus` VARCHAR(20) NULL,
  `PartFileName` VARCHAR(45) NULL,
  `PartQuoteFileName` VARCHAR(45) NULL,
  `PartAMFileName` VARCHAR(45) NULL,
  `PartFinish` VARCHAR(45) NULL,
  `PartQuantity` INT NULL,
  PRIMARY KEY (`idPart`, `DataSet_idDataSet`, `PrintParameters_idPrintParameters`),
  INDEX `fk_Part_DataSet1_idx` (`DataSet_idDataSet` ASC),
  INDEX `fk_Part_PrintParameters1_idx` (`PrintParameters_idPrintParameters` ASC),
  CONSTRAINT `fk_Part_DataSet1`
    FOREIGN KEY (`DataSet_idDataSet`)
    REFERENCES `hmat`.`DataSet` (`idDataSet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Part_PrintParameters1`
    FOREIGN KEY (`PrintParameters_idPrintParameters`)
    REFERENCES `hmat`.`PrintParameters` (`idPrintParameters`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmat`.`Demand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmat`.`Demand` ;

CREATE TABLE IF NOT EXISTS `hmat`.`Demand` (
  `idDemand` INT NOT NULL AUTO_INCREMENT,
  `Quote_idQuote` INT NOT NULL,
  `DemandStatus` VARCHAR(20) NULL,
  `DemandDateReceived` DATETIME NULL,
  `DemandDateConfirmed` DATETIME NULL,
  `DemandPostProcessStart` DATETIME NULL,
  `DemandPostProcessEnd` DATETIME NULL,
  `DemandCheckedBy` VARCHAR(45) NULL,
  `DemandCheckDate` DATETIME NULL,
  PRIMARY KEY (`idDemand`, `Quote_idQuote`),
  INDEX `fk_Order_Quote1_idx` (`Quote_idQuote` ASC),
  CONSTRAINT `fk_Order_Quote1`
    FOREIGN KEY (`Quote_idQuote`)
    REFERENCES `hmat`.`Quote` (`idQuote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmat`.`StatusLog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmat`.`StatusLog` ;

CREATE TABLE IF NOT EXISTS `hmat`.`StatusLog` (
  `idStatusLog` INT NOT NULL AUTO_INCREMENT,
  `StatusLogTable` VARCHAR(20) NULL,
  `StatusLogRowId` INT NULL,
  `StatusLogStatus` VARCHAR(20) NULL,
  `StatusLogTimestamp` TIMESTAMP(6) NULL,
  PRIMARY KEY (`idStatusLog`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmat`.`Invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmat`.`Invoice` ;

CREATE TABLE IF NOT EXISTS `hmat`.`Invoice` (
  `idInvoice` INT NOT NULL AUTO_INCREMENT,
  `Order_idOrder` INT NOT NULL,
  `InvoiceStatus` VARCHAR(20) NULL,
  `InvoiceIssued` DATETIME NULL,
  `InvoicePaymentTerm` INT NULL,
  `InvoiceTotal` FLOAT NULL,
  `InvoiceVAT` FLOAT NULL,
  `InvoiceType` VARCHAR(15) NULL,
  PRIMARY KEY (`idInvoice`, `Order_idOrder`),
  INDEX `fk_Invoice_Order1_idx` (`Order_idOrder` ASC),
  CONSTRAINT `fk_Invoice_Order1`
    FOREIGN KEY (`Order_idOrder`)
    REFERENCES `hmat`.`Demand` (`idDemand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmat`.`Platform`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmat`.`Platform` ;

CREATE TABLE IF NOT EXISTS `hmat`.`Platform` (
  `idPlatform` INT NOT NULL AUTO_INCREMENT,
  `PlatformName` VARCHAR(45) NULL,
  PRIMARY KEY (`idPlatform`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmat`.`Build`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmat`.`Build` ;

CREATE TABLE IF NOT EXISTS `hmat`.`Build` (
  `idBuild` INT NOT NULL AUTO_INCREMENT,
  `BuildStatus` VARCHAR(20) NULL,
  `BuildRequested` DATETIME NULL,
  `BuildPrintJobStart` DATETIME NULL,
  `BuildPrintJobEnd` DATETIME NULL,
  `Platform_idPlatform` INT NOT NULL,
  PRIMARY KEY (`idBuild`, `Platform_idPlatform`),
  INDEX `fk_Build_Platform1_idx` (`Platform_idPlatform` ASC),
  CONSTRAINT `fk_Build_Platform1`
    FOREIGN KEY (`Platform_idPlatform`)
    REFERENCES `hmat`.`Platform` (`idPlatform`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmat`.`Platform_has_Part`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmat`.`Platform_has_Part` ;

CREATE TABLE IF NOT EXISTS `hmat`.`Platform_has_Part` (
  `Platform_idPlatform` INT NOT NULL,
  `Part_idPart` INT NOT NULL,
  `PartQuantity` INT NULL,
  PRIMARY KEY (`Platform_idPlatform`, `Part_idPart`),
  INDEX `fk_Platform_has_Part_Part1_idx` (`Part_idPart` ASC),
  INDEX `fk_Platform_has_Part_Platform1_idx` (`Platform_idPlatform` ASC),
  CONSTRAINT `fk_Platform_has_Part_Platform1`
    FOREIGN KEY (`Platform_idPlatform`)
    REFERENCES `hmat`.`Platform` (`idPlatform`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Platform_has_Part_Part1`
    FOREIGN KEY (`Part_idPart`)
    REFERENCES `hmat`.`Part` (`idPart`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmat`.`DeliveryNote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmat`.`DeliveryNote` ;

CREATE TABLE IF NOT EXISTS `hmat`.`DeliveryNote` (
  `idDeliveryNote` INT NOT NULL,
  `Invoice_idInvoice` INT NOT NULL,
  `DeliveryNoteStatus` VARCHAR(20) NULL,
  `DeliveryNoteIssued` DATETIME NULL,
  `DeliveryNoteSigned` DATETIME NULL,
  `ShippingAddress` VARCHAR(45) NULL,
  PRIMARY KEY (`idDeliveryNote`, `Invoice_idInvoice`),
  INDEX `fk_DeliveryNote_Invoice1_idx` (`Invoice_idInvoice` ASC),
  CONSTRAINT `fk_DeliveryNote_Invoice1`
    FOREIGN KEY (`Invoice_idInvoice`)
    REFERENCES `hmat`.`Invoice` (`idInvoice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmat`.`DeliveryTransport`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmat`.`DeliveryTransport` ;

CREATE TABLE IF NOT EXISTS `hmat`.`DeliveryTransport` (
  `iddeliveryTransport` INT NOT NULL,
  `DeliveryNote_idDeliveryNote` INT NOT NULL,
  `deliveryTransportMethod` VARCHAR(45) NULL,
  `deliveryTransportOption` VARCHAR(10) NULL,
  `deliveryTransportDate` DATE NULL,
  `deliveryTransportPayment` VARCHAR(45) NULL,
  PRIMARY KEY (`iddeliveryTransport`, `DeliveryNote_idDeliveryNote`),
  INDEX `fk_deliveryTransport_DeliveryNote1_idx` (`DeliveryNote_idDeliveryNote` ASC),
  CONSTRAINT `fk_deliveryTransport_DeliveryNote1`
    FOREIGN KEY (`DeliveryNote_idDeliveryNote`)
    REFERENCES `hmat`.`DeliveryNote` (`idDeliveryNote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmat`.`GlobalSettings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmat`.`GlobalSettings` ;

CREATE TABLE IF NOT EXISTS `hmat`.`GlobalSettings` (
  `idSettings` INT NOT NULL,
  `GlobalCurrency` VARCHAR(3) NULL,
  `VAT` INT NULL,
  `Language` VARCHAR(20) NULL,
  `GlobalSettingMyCompany` VARCHAR(45) NULL,
  PRIMARY KEY (`idSettings`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmat`.`Note`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmat`.`Note` ;

CREATE TABLE IF NOT EXISTS `hmat`.`Note` (
  `idNote` INT NOT NULL AUTO_INCREMENT,
  `NoteTable` VARCHAR(15) NULL,
  `NoteRowId` INT NULL,
  `NoteText` VARCHAR(200) NULL,
  `NoteTime` TIMESTAMP(6) NULL,
  PRIMARY KEY (`idNote`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
