-- MySQL Script generated by MySQL Workbench
-- 04/06/16 20:20:38
-- Model: hmat    Version: 0.1

-- work flow monitor

-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hmat_dev
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hmat_dev` ;

-- -----------------------------------------------------
-- Schema hmat_dev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hmat_dev` DEFAULT CHARACTER SET utf8 COLLATE utf8_slovak_ci ;
USE `hmat_dev` ;

-- -----------------------------------------------------
-- Table `hmat_dev`.`Industry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmat_dev`.`Industry` ;

CREATE TABLE IF NOT EXISTS `hmat_dev`.`Industry` (
  `idIndustry` INT NOT NULL AUTO_INCREMENT,
  `IndustryShortcut` VARCHAR(5) NOT NULL,
  `IndustryName` VARCHAR(45) NULL,
  PRIMARY KEY (`idIndustry`),
  UNIQUE INDEX `IndustryShortcut_UNIQUE` (`IndustryShortcut` ASC),
  UNIQUE INDEX `IndustryName_UNIQUE` (`IndustryName` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmat_dev`.`Company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmat_dev`.`Company` ;

CREATE TABLE IF NOT EXISTS `hmat_dev`.`Company` (
  `idCompany` INT NOT NULL AUTO_INCREMENT,
  `Company_idIndustry` INT NOT NULL,
  `CompanyName` VARCHAR(30) NULL,
  `CompanyICO` VARCHAR(25) NULL,
  `CompanyDIC` VARCHAR(25) NULL,
  `CompanyDRC` VARCHAR(20) NULL,
  `CompanyWebsite` VARCHAR(45) NULL,
  PRIMARY KEY (`idCompany`, `Company_idIndustry`),
  INDEX `fk_Company_Industry1_idx` (`Company_idIndustry` ASC),
  UNIQUE INDEX `CompanyName_UNIQUE` (`CompanyName` ASC),
  UNIQUE INDEX `CompanyICO_UNIQUE` (`CompanyICO` ASC),
  UNIQUE INDEX `CompanyDIC_UNIQUE` (`CompanyDIC` ASC),
  UNIQUE INDEX `CompanyDRC_UNIQUE` (`CompanyDRC` ASC),
  CONSTRAINT `fk_Company_Industry1`
    FOREIGN KEY (`Company_idIndustry`)
    REFERENCES `hmat_dev`.`Industry` (`idIndustry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmat_dev`.`Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmat_dev`.`Address` ;

CREATE TABLE IF NOT EXISTS `hmat_dev`.`Address` (
  `idAddress` INT NOT NULL AUTO_INCREMENT,
  `Address_idCompany` INT NOT NULL,
  `AddressName` VARCHAR(45) NULL,
  `AddressStreet` VARCHAR(60) NULL,
  `AddressNumber` VARCHAR(20) NULL,
  `AddressZip` VARCHAR(10) NULL,
  `AddressCity` VARCHAR(30) NULL,
  `AddressCountry` VARCHAR(30) NULL,
  PRIMARY KEY (`idAddress`, `Address_idCompany`),
  INDEX `fk_Address_Company1_idx` (`Address_idCompany` ASC),
  CONSTRAINT `fk_Address_Company1`
    FOREIGN KEY (`Address_idCompany`)
    REFERENCES `hmat_dev`.`Company` (`idCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmat_dev`.`Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmat_dev`.`Account` ;

CREATE TABLE IF NOT EXISTS `hmat_dev`.`Account` (
  `idAccount` INT NOT NULL AUTO_INCREMENT,
  `Account_idCompany` INT NOT NULL,
  `AccountName` VARCHAR(30) NULL,
  `AccountBank` VARCHAR(30) NULL,
  `AccountVAT` VARCHAR(45) NULL,
  `AccountIBAN` VARCHAR(30) NULL,
  PRIMARY KEY (`idAccount`, `Account_idCompany`),
  INDEX `fk_Account_Company1_idx` (`Account_idCompany` ASC),
  CONSTRAINT `fk_Account_Company1`
    FOREIGN KEY (`Account_idCompany`)
    REFERENCES `hmat_dev`.`Company` (`idCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmat_dev`.`Person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmat_dev`.`Person` ;

CREATE TABLE IF NOT EXISTS `hmat_dev`.`Person` (
  `idPerson` INT NOT NULL AUTO_INCREMENT,
  `Person_idCompany` INT NOT NULL,
  `PersonName` VARCHAR(20) NULL,
  `PersonSurname` VARCHAR(45) NULL,
  `PersonPostition` VARCHAR(20) NULL,
  `PersonPhone` VARCHAR(30) NULL,
  `PersonEmail` VARCHAR(45) NULL,
  PRIMARY KEY (`idPerson`, `Person_idCompany`),
  INDEX `fk_Person_Company1_idx` (`Person_idCompany` ASC),
  CONSTRAINT `fk_Person_Company1`
    FOREIGN KEY (`Person_idCompany`)
    REFERENCES `hmat_dev`.`Company` (`idCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmat_dev`.`Project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmat_dev`.`Project` ;

CREATE TABLE IF NOT EXISTS `hmat_dev`.`Project` (
  `idProject` INT NOT NULL AUTO_INCREMENT,
  `Project_idCompany` INT NOT NULL,
  `ProjectStartDate` DATETIME NULL,
  `ProjectStatus` VARCHAR(20) NULL,
  `ProjectName` VARCHAR(45) NULL,
  `ProjectPriority` INT NULL,
  PRIMARY KEY (`idProject`, `Project_idCompany`),
  INDEX `fk_Project_Company1_idx` (`Project_idCompany` ASC),
  CONSTRAINT `fk_Project_Company1`
    FOREIGN KEY (`Project_idCompany`)
    REFERENCES `hmat_dev`.`Company` (`idCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmat_dev`.`PrintParameters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmat_dev`.`PrintParameters` ;

CREATE TABLE IF NOT EXISTS `hmat_dev`.`PrintParameters` (
  `idPrintParameters` INT NOT NULL AUTO_INCREMENT,
  `PrintParametersTechnology` VARCHAR(20) NULL,
  `PrintParametersMaterial` VARCHAR(20) NULL,
  `PrintParametersResolution` VARCHAR(20) NULL,
  `PrintParametersLayer` VARCHAR(20) NULL,
  `PrintParametersFinish` VARCHAR(40) NULL,
  PRIMARY KEY (`idPrintParameters`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmat_dev`.`Quote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmat_dev`.`Quote` ;

CREATE TABLE IF NOT EXISTS `hmat_dev`.`Quote` (
  `idQuote` INT NOT NULL AUTO_INCREMENT,
  `Quote_idProject` INT NOT NULL,
  `Quote_idPrintParameters` INT NOT NULL,
  `QuoteStatus` VARCHAR(15) NULL,
  `QuoteLeadTime` TIME(6) NULL,
  `QuotePrice` FLOAT NULL,
  `QuoteDateSent` DATETIME NULL,
  PRIMARY KEY (`idQuote`, `Quote_idProject`, `Quote_idPrintParameters`),
  INDEX `fk_Quote_Project1_idx` (`Quote_idProject` ASC),
  INDEX `fk_Quote_PrintParameters1_idx` (`Quote_idPrintParameters` ASC),
  CONSTRAINT `fk_Quote_Project1`
    FOREIGN KEY (`Quote_idProject`)
    REFERENCES `hmat_dev`.`Project` (`idProject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Quote_PrintParameters1`
    FOREIGN KEY (`Quote_idPrintParameters`)
    REFERENCES `hmat_dev`.`PrintParameters` (`idPrintParameters`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmat_dev`.`DataSet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmat_dev`.`DataSet` ;

CREATE TABLE IF NOT EXISTS `hmat_dev`.`DataSet` (
  `idDataSet` INT NOT NULL AUTO_INCREMENT,
  `DataSet_idPrintParameters` INT NOT NULL,
  `DataSet_idQuote` INT NOT NULL,
  `DataSetName` VARCHAR(30) NULL,
  `DataSetStatus` VARCHAR(20) NULL,
  `DataSetDate` DATETIME NULL,
  PRIMARY KEY (`idDataSet`, `DataSet_idPrintParameters`, `DataSet_idQuote`),
  INDEX `fk_DataSet_Quote1_idx` (`DataSet_idQuote` ASC),
  INDEX `fk_DataSet_PrintParameters1_idx` (`DataSet_idPrintParameters` ASC),
  CONSTRAINT `fk_DataSet_Quote1`
    FOREIGN KEY (`DataSet_idQuote`)
    REFERENCES `hmat_dev`.`Quote` (`idQuote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DataSet_PrintParameters1`
    FOREIGN KEY (`DataSet_idPrintParameters`)
    REFERENCES `hmat_dev`.`PrintParameters` (`idPrintParameters`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmat_dev`.`Part`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmat_dev`.`Part` ;

CREATE TABLE IF NOT EXISTS `hmat_dev`.`Part` (
  `idPart` INT NOT NULL AUTO_INCREMENT,
  `Part_idDataSet` INT NOT NULL,
  `Part_idPrintParameters` INT NOT NULL,
  `PartStatus` VARCHAR(20) NULL,
  `PartFileName` VARCHAR(45) NULL,
  `PartQuoteFileName` VARCHAR(45) NULL,
  `PartAMFileName` VARCHAR(45) NULL,
  `PartFinish` VARCHAR(45) NULL,
  `PartQuantity` INT NULL,
  PRIMARY KEY (`idPart`, `Part_idDataSet`, `Part_idPrintParameters`),
  INDEX `fk_Part_DataSet1_idx` (`Part_idDataSet` ASC),
  INDEX `fk_Part_PrintParameters1_idx` (`Part_idPrintParameters` ASC),
  CONSTRAINT `fk_Part_DataSet1`
    FOREIGN KEY (`Part_idDataSet`)
    REFERENCES `hmat_dev`.`DataSet` (`idDataSet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Part_PrintParameters1`
    FOREIGN KEY (`Part_idPrintParameters`)
    REFERENCES `hmat_dev`.`PrintParameters` (`idPrintParameters`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmat_dev`.`Demand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmat_dev`.`Demand` ;

CREATE TABLE IF NOT EXISTS `hmat_dev`.`Demand` (
  `idDemand` INT NOT NULL AUTO_INCREMENT,
  `Demand_idQuote` INT NOT NULL,
  `DemandStatus` VARCHAR(20) NULL,
  `DemandDateReceived` DATETIME NULL,
  `DemandDateConfirmed` DATETIME NULL,
  `DemandPostProcessStart` DATETIME NULL,
  `DemandPostProcessEnd` DATETIME NULL,
  `DemandCheckedBy` VARCHAR(45) NULL,
  `DemandCheckDate` DATETIME NULL,
  PRIMARY KEY (`idDemand`, `Demand_idQuote`),
  INDEX `fk_Order_Quote1_idx` (`Demand_idQuote` ASC),
  CONSTRAINT `fk_Order_Quote1`
    FOREIGN KEY (`Demand_idQuote`)
    REFERENCES `hmat_dev`.`Quote` (`idQuote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmat_dev`.`StatusLog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmat_dev`.`StatusLog` ;

CREATE TABLE IF NOT EXISTS `hmat_dev`.`StatusLog` (
  `idStatusLog` INT NOT NULL AUTO_INCREMENT,
  `StatusLogTable` VARCHAR(20) NULL,
  `StatusLogRowId` INT NULL,
  `StatusLogStatus` VARCHAR(20) NULL,
  `StatusLogTimestamp` TIMESTAMP(6) NULL,
  PRIMARY KEY (`idStatusLog`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmat_dev`.`Invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmat_dev`.`Invoice` ;

CREATE TABLE IF NOT EXISTS `hmat_dev`.`Invoice` (
  `idInvoice` INT NOT NULL AUTO_INCREMENT,
  `Invoice_idOrder` INT NOT NULL,
  `InvoiceStatus` VARCHAR(20) NULL,
  `InvoiceIssued` DATETIME NULL,
  `InvoicePaymentTerm` INT NULL,
  `InvoiceTotal` FLOAT NULL,
  `InvoiceVAT` FLOAT NULL,
  `InvoiceType` VARCHAR(15) NULL,
  PRIMARY KEY (`idInvoice`, `Invoice_idOrder`),
  INDEX `fk_Invoice_Order1_idx` (`Invoice_idOrder` ASC),
  CONSTRAINT `fk_Invoice_Order1`
    FOREIGN KEY (`Invoice_idOrder`)
    REFERENCES `hmat_dev`.`Demand` (`idDemand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmat_dev`.`Platform`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmat_dev`.`Platform` ;

CREATE TABLE IF NOT EXISTS `hmat_dev`.`Platform` (
  `idPlatform` INT NOT NULL AUTO_INCREMENT,
  `PlatformName` VARCHAR(45) NULL,
  PRIMARY KEY (`idPlatform`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmat_dev`.`Build`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmat_dev`.`Build` ;

CREATE TABLE IF NOT EXISTS `hmat_dev`.`Build` (
  `idBuild` INT NOT NULL AUTO_INCREMENT,
  `Build_idPlatform` INT NOT NULL,
  `BuildStatus` VARCHAR(20) NULL,
  `BuildRequested` DATETIME NULL,
  `BuildPrintJobStart` DATETIME NULL,
  `BuildPrintJobEnd` DATETIME NULL,
  PRIMARY KEY (`idBuild`, `Build_idPlatform`),
  INDEX `fk_Build_Platform1_idx` (`Build_idPlatform` ASC),
  CONSTRAINT `fk_Build_Platform1`
    FOREIGN KEY (`Build_idPlatform`)
    REFERENCES `hmat_dev`.`Platform` (`idPlatform`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmat_dev`.`Platform_has_Part`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmat_dev`.`Platform_has_Part` ;

CREATE TABLE IF NOT EXISTS `hmat_dev`.`Platform_has_Part` (
  `Platform_idPlatform` INT NOT NULL,
  `Part_idPart` INT NOT NULL,
  `PartQuantity` INT NULL,
  PRIMARY KEY (`Platform_idPlatform`, `Part_idPart`),
  INDEX `fk_Platform_has_Part_Part1_idx` (`Part_idPart` ASC),
  INDEX `fk_Platform_has_Part_Platform1_idx` (`Platform_idPlatform` ASC),
  CONSTRAINT `fk_Platform_has_Part_Platform1`
    FOREIGN KEY (`Platform_idPlatform`)
    REFERENCES `hmat_dev`.`Platform` (`idPlatform`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Platform_has_Part_Part1`
    FOREIGN KEY (`Part_idPart`)
    REFERENCES `hmat_dev`.`Part` (`idPart`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmat_dev`.`DeliveryNote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmat_dev`.`DeliveryNote` ;

CREATE TABLE IF NOT EXISTS `hmat_dev`.`DeliveryNote` (
  `idDeliveryNote` INT NOT NULL AUTO_INCREMENT,
  `DeliveryNote_idInvoice` INT NOT NULL,
  `DeliveryNoteStatus` VARCHAR(20) NULL,
  `DeliveryNoteIssued` DATETIME NULL,
  `DeliveryNoteSigned` DATETIME NULL,
  `ShippingAddress` VARCHAR(45) NULL,
  PRIMARY KEY (`idDeliveryNote`, `DeliveryNote_idInvoice`),
  INDEX `fk_DeliveryNote_Invoice1_idx` (`DeliveryNote_idInvoice` ASC),
  CONSTRAINT `fk_DeliveryNote_Invoice1`
    FOREIGN KEY (`DeliveryNote_idInvoice`)
    REFERENCES `hmat_dev`.`Invoice` (`idInvoice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmat_dev`.`DeliveryTransport`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmat_dev`.`DeliveryTransport` ;

CREATE TABLE IF NOT EXISTS `hmat_dev`.`DeliveryTransport` (
  `idDeliveryTransport` INT NOT NULL AUTO_INCREMENT,
  `DeliveryTransport_idDeliveryNote` INT NOT NULL,
  `deliveryTransportMethod` VARCHAR(45) NULL,
  `deliveryTransportOption` VARCHAR(10) NULL,
  `deliveryTransportDate` DATE NULL,
  `deliveryTransportPayment` VARCHAR(45) NULL,
  PRIMARY KEY (`idDeliveryTransport`, `DeliveryTransport_idDeliveryNote`),
  INDEX `fk_deliveryTransport_DeliveryNote1_idx` (`DeliveryTransport_idDeliveryNote` ASC),
  CONSTRAINT `fk_deliveryTransport_DeliveryNote1`
    FOREIGN KEY (`DeliveryTransport_idDeliveryNote`)
    REFERENCES `hmat_dev`.`DeliveryNote` (`idDeliveryNote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmat_dev`.`Note`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmat_dev`.`Note` ;

CREATE TABLE IF NOT EXISTS `hmat_dev`.`Note` (
  `idNote` INT NOT NULL AUTO_INCREMENT,
  `NoteTable` VARCHAR(15) NULL,
  `NoteRowId` INT NULL,
  `NoteText` VARCHAR(200) NULL,
  `NoteTime` TIMESTAMP(6) NULL,
  PRIMARY KEY (`idNote`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmat_dev`.`GUI`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmat_dev`.`GUI` ;

CREATE TABLE IF NOT EXISTS `hmat_dev`.`GUI` (
  `idGUI` INT NOT NULL AUTO_INCREMENT,
  `GUIelement` VARCHAR(45) NULL,
  `GUIattribute` VARCHAR(45) NULL,
  `GUIvalue` VARCHAR(45) NULL,
  PRIMARY KEY (`idGUI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hmat_dev`.`Status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hmat_dev`.`Status` ;

CREATE TABLE IF NOT EXISTS `hmat_dev`.`Status` (
  `idStatus` INT NOT NULL AUTO_INCREMENT,
  `StatusType` VARCHAR(20) NULL,
  `StatusName` VARCHAR(20) NULL,
  `StatusColor` VARCHAR(7) NULL,
  PRIMARY KEY (`idStatus`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
