SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

INSERT INTO `gui` (`idGUI`, `GUIelement`, `GUIattribute`, `GUIvalue`) VALUES
(54, 'tabButtonNoteNote', 'ENG', 'Note'),
(55, 'tabButtonStatusStatus', 'ENG', 'State'),
(56, 'tabButtonStatusStatusLog', 'ENG', 'Status History'),
(57, 'tabButtonStatusLogStatusLog', 'ENG', 'StatusLog'),
(58, 'tabButtonGUIGUI', 'ENG', 'OM'),
(73, 'tabButtonStatusNote', 'ENG', 'Notes'),
(91, 'tabButtonStatusLogNote', 'ENG', 'Note'),
(92, 'tabButtonGUINote', 'ENG', 'Notes'),
(114, 'tabButtonAdminNote', 'ENG', 'Notes'),
(121, 'tabButtonAdminStatus', 'ENG', 'States'),
(122, 'tabButtonAdminStatusLog', 'ENG', 'States Log'),
(123, 'tabGUIGUI', 'ENG', 'OM'),
(139, 'GUIORDERidGUI', 'ENG', '#'),
(140, 'GUIORDERGUIelement', 'ENG', 'element'),
(141, 'GUIORDERGUIattribute', 'ENG', 'attribute'),
(142, 'GUIORDERGUIvalue', 'ENG', 'value'),
(179, 'StatusLogORDERStatusLogTimestamp', 'ENG', 'Timestamp'),
(180, 'StatusLogORDERidStatusLog', 'ENG', '#'),
(190, 'tabButtonNoteStatus', 'ENG', 'State'),
(192, 'tabButtonStatusLogStatus', 'ENG', 'State'),
(211, 'StatusLogORDERStatusName', 'ENG', 'State'),
(212, 'NoteORDERidNote', 'ENG', '#'),
(213, 'NoteORDERNoteText', 'ENG', 'Note'),
(214, 'NoteORDERStatusName', 'ENG', 'State'),
(215, 'NoteORDERNoteTime', 'ENG', 'Time'),
(264, 'StatusORDERidStatus', 'ENG', '#'),
(265, 'StatusORDERStatusType', 'ENG', 'Type'),
(266, 'StatusORDERStatusName', 'ENG', 'State'),
(267, 'StatusORDERStatusColor', 'ENG', 'Color'),
(291, 'tabAdminNote', 'ENG', 'Notes'),
(292, 'tabAdminStatus', 'ENG', 'States'),
(293, 'tabAdminStatusLog', 'ENG', 'States Log'),
(294, 'tabAdminGUI', 'ENG', 'OM'),
(331, 'tabStatusNote', 'ENG', 'Notes'),
(336, 'tabStatusStatusLog', 'ENG', 'Status History'),
(337, 'tabGUINote', 'ENG', 'Notes'),
(353, 'NoteInsert', 'ENG', '+ Note'),
(354, 'StatusLogInsert', 'ENG', '+ History'),
(355, 'GUIInsert', 'ENG', '+ GUI'),
(356, 'StatusInsert', 'ENG', '+ Status'),
(399, 'ActionORDERidAction', 'ENG', '#'),
(400, 'ActionORDERActionName', 'ENG', 'Name'),
(401, 'ActionORDERActionSequence', 'ENG', 'Sequence'),
(402, 'ActionORDERActionTable', 'ENG', 'Table'),
(403, 'ActionORDERActionField', 'ENG', 'Field'),
(404, 'ActionORDERActionCommand', 'ENG', 'Command'),
(405, 'ActionORDERActionParam1', 'ENG', 'Parameter 1'),
(406, 'ActionORDERActionParam2', 'ENG', 'Parameter 2'),
(419, 'RelationORDERidRelation', 'ENG', '#'),
(420, 'RelationORDERRelationRightTable', 'ENG', 'Connect to Table'),
(421, 'RelationORDERRelationRightId', 'ENG', 'Connect to Record'),
(422, 'RelationORDERRelationLeftTable', 'ENG', 'Connected Table'),
(423, 'RelationORDERRelationLeftId', 'ENG', 'Connected Record'),
(444, 'RelationLeft', 'ENG', '--->'),
(445, 'RelationRight', 'ENG', '>---'),
(458, 'RelationORDERRelationRObject', 'ENG', 'Connected to Object Type'),
(459, 'RelationORDERRelationRId', 'ENG', 'Connected to Object Name'),
(460, 'RelationORDERRelationLObject', 'ENG', 'Connected Object Type'),
(461, 'RelationORDERRelationLId', 'ENG', 'Connected Object Name'),
(471, 'TaskORDERidTask', 'ENG', '#'),
(472, 'TaskORDERTaskName', 'ENG', 'Name'),
(473, 'TaskORDERTaskSequence', 'ENG', 'Sequence'),
(474, 'TaskORDERTaskDuration', 'ENG', 'Duration'),
(475, 'TaskORDERparentTaskName', 'ENG', 'Parent Task'),
(476, 'JobORDERidJob', 'ENG', '#'),
(477, 'JobORDERJobName', 'ENG', 'Description'),
(478, 'JobORDERJobCreated', 'ENG', 'Created'),
(479, 'JobORDERJobStarted', 'ENG', 'Started'),
(480, 'JobORDERJobFinished', 'ENG', 'Finished'),
(481, 'JobORDERJobDeadline', 'ENG', 'Deadline'),
(482, 'JobORDERStatusName', 'ENG', 'State'),
(483, 'JobORDERTaskName', 'ENG', 'Task'),
(484, 'tabButtonJobRelationLeft', 'ENG', '--->'),
(485, 'tabJobRelationLeft', 'ENG', '--->'),
(486, 'tabButtonJobRelationRight', 'ENG', '>---'),
(487, 'tabJobRelationRight', 'ENG', '>---'),
(488, 'tabButtonJobNote', 'ENG', 'Notes'),
(489, 'tabJobStatus', 'ENG', 'History'),
(490, 'tabButtonJobStatus', 'ENG', 'History'),
(491, 'tabJobNote', 'ENG', 'Notes'),
(492, 'StatusLogORDERStatusType', 'ENG', 'Status Type'),
(493, 'tabGUIRelationLeft', 'ENG', '--->'),
(494, 'tabButtonGUIRelationLeft', 'ENG', '--->'),
(495, 'tabGUIRelationRight', 'ENG', '>---'),
(496, 'tabButtonGUIRelationRight', 'ENG', '>---'),
(497, 'tabButtonAdminAction', 'ENG', 'Automation'),
(498, 'tabButtonAdminRelation', 'ENG', 'Relations'),
(499, 'tabButtonAdminJob', 'ENG', 'Jobs'),
(500, 'tabButtonAdminTask', 'ENG', 'Moves'),
(502, 'tabButtonTaskJob', 'ENG', 'Jobs'),
(503, 'tabTaskJob', 'ENG', 'Jobs'),
(504, 'tabTaskTask', 'ENG', 'Moves'),
(505, 'tabButtonTaskTask', 'ENG', 'Moves'),
(506, 'tabTaskRelationLeft', 'ENG', '--->'),
(507, 'tabButtonTaskRelationLeft', 'ENG', '--->'),
(508, 'tabTaskRelationRight', 'ENG', '>---'),
(509, 'tabButtonTaskRelationRight', 'ENG', '>---'),
(510, 'tabButtonTaskNote', 'ENG', 'Notes'),
(511, 'tabTaskNote', 'ENG', 'Notes'),
(512, 'tabAdminJob', 'ENG', 'Jobs'),
(513, 'tabAdminTask', 'ENG', 'Moves'),
(514, 'tabAdminAction', 'ENG', 'Automation'),
(515, 'tabAdminRelation', 'ENG', 'Relations'),
(516, 'JobORDERJobPriority', 'ENG', 'Priority'),
(518, 'tabButtonAdminGUI', 'ENG', 'OM'),
(523, 'Relation', 'color', ' #e0e2e4'),
(524, 'tabButtonRelationRight', 'ENG', '>---'),
(525, 'tabRelationRight', 'ENG', '>---'),
(526, 'tabRelationLeft', 'ENG', '--->'),
(527, 'tabButtonRelationLeft', 'ENG', '--->'),
(536, 'GUI', 'color', ' #ccccb3'),
(537, 'StatusLog', 'color', '#c8c3cc'),
(538, 'History', 'color', '#c8c3cc'),
(539, 'Note', 'color', '#c6bcb6'),
(552, 'Status', 'lookupField', 'StatusName'),
(560, 'Task', 'lookupField', 'TaskName'),
(575, 'Action', 'color', 'lightgray'),
(585, 'Job', 'color', 'lightgray'),
(596, 'Status', 'color', 'lightgray'),
(598, 'Task', 'color', 'lightgray'),
(602, 'tabButtonNote', 'ENG', 'Note'),
(603, 'tabStatus', 'ENG', 'Status'),
(604, 'tabButtonAdminHistory', 'ENG', 'History'),
(610, 'Note', 'displayColumnNames', 'idNote,NoteText,NoteTime'),
(611, 'Relation', 'displayColumnNames', 'idRelation,RelationType,RelationLObject,RelationLId,RelationRObject,RelationRId'),
(612, 'StatusLog', 'displayColumnNames', 'idStatusLog,StatusLogTimestamp,StatusType,StatusName'),
(618, 'Action', 'displayColumnNames', 'idAction,ActionName,ActionSequence,ActionTable,ActionField,ActionCommand,ActionParam1'),
(622, 'GUI', 'displayColumnNames', 'idGUI,GUIelement,GUIattribute,GUIvalue'),
(623, 'History', 'displayColumnNames', 'idHistory,HistoryTable,HistoryRowId,HistoryCommand,HistorySQL,HistoryTimestamp'),
(625, 'Job', 'displayColumnNames', 'idJob,JobName,JobCreated,JobStarted,JobFinished,JobDeadline,JobPriority,StatusName,TaskName'),
(631, 'Status', 'displayColumnNames', 'idStatus,StatusType,StatusName,StatusColor,StatusFlags,StatusSequence'),
(632, 'Task', 'displayColumnNames', 'idTask,TaskName,TaskSequence,TaskDuration,parentTaskName'),
(637, 'tabNote', 'ENG', 'Note'),
(639, 'tabButtonStatus', 'ENG', 'Status'),
(648, 'HistoryORDERidHistory', 'ENG', 'idHistory'),
(649, 'HistoryORDERHistoryTable', 'ENG', 'HistoryTable'),
(650, 'HistoryORDERHistoryRowId', 'ENG', 'HistoryRowId'),
(651, 'HistoryORDERHistoryCommand', 'ENG', 'HistoryCommand'),
(652, 'HistoryORDERHistorySQL', 'ENG', 'HistorySQL'),
(653, 'HistoryORDERHistoryTimestamp', 'ENG', 'HistoryTimestamp'),
(654, 'tabAdminHistory', 'ENG', 'History'),
(665, 'RelationORDERRelationType', 'ENG', 'RelationType'),
(667, 'StatusORDERStatusFlags', 'ENG', 'StatusFlags'),
(679, 'Relation', 'lookupField', 'RelationName'),
(680, 'GUI', 'lookupField', 'GUIName'),
(688, 'tabButtonJob', 'ENG', 'Job'),
(698, 'StatusORDERStatusSequence', 'ENG', 'StatusSequence'),
(706, 'tabButtonStatusLog', 'ENG', 'StatusLog'),
(722, 'tabStatusLog', 'ENG', 'StatusLog');
